pivotal-cf/docs-ksm

docs-book/master_middleman/source/subnavs/bazaar_subnav.erb
docs-content/index.html.md.erb
docs-content/installing.html.md.erb
docs-content/release-notes.html.md.erb
docs-content/using.html.md.erb

We have a little bit of placeholder text in place (the `deeppink` formatted) - the tile version, for example.
cc @beazer @aaronmeza

Initial Release Version of Docs

---

README.md
index.html.md.erb
installing.html.md.erb
using.html.md.erb

Please make this available only for the next KSM release.
This is not a retroactive change.
Tracker #165979731

Renaming references from bazaar to ksm.

---

architecture.html.md.erb

https://github.com/pivotal-cf/docs-book-ksm/pull/5 should be merged at the same time.

Finish first version of architecture page

---

release-notes.html.md.erb

the description of the known issue is still correct.

word-smithed the explanation of the bug fix

---

using.html.md.erb

Please include this in both master and `0.5` branch.

Docment Service Instances Can't Be Deleted

---

prepare-offer.html.md.erb
troubleshoot.html.md.erb
using.html.md.erb

This is doc changes for our next release (unscheduled as of now), 0.7.x, so PRing to master.
[#170287520]
Co-authored-by: Eduardo Oliveira <edeoliveira@pivotal.io>

Documentation update to reflect helm 3 changes.

---

prepare-offer.html.md.erb

Add info on helm chart best practices 

---

prepare-offer.html.md.erb

Co-authored-by: Eduardo De Oliveira <edeoliveira@pivotal.io>

add documentation for `ksm offer init`

---

prepare-offer.html.md.erb

Add a note about `-c` flag and add accurate `test-bind-template` output.

A few more doc tweaks.

---

architecture.html.md.erb
prepare-offer.html.md.erb
troubleshoot.html.md.erb
using.html.md.erb

Co-authored-by: Jeenal Shah <jshah@pivotal.io>

Some changes due to kibosh name removal

---

prepare-offer.html.md.erb

Add docs for new feature for ResourceQuotas
Co-authored by: Maggie Ambrose <mambrose@pivotal.io>
[#171151597]

Add docs for new feature for ResourceQuotas

---

troubleshoot.html.md.erb

[#168847909]
Co-authored-by: Matt Cholick <mcholick@pivotal.io>

OSBAPI Metadata is in a configmap in the Kubernetes namespace

---

release-notes.html.md.erb

Co-authored-by: Emily Johnson <ejohnson@pivotal.io>

Add release notes for 0.7.x release

---

prepare-offer.html.md.erb

Co-authored-by: Maggie Ambrose <mambrose@pivotal.io>

Make overrides plural to match other directories

---

release-notes.html.md.erb

OSL in progress (hopefully released next week)
Co-authored-by: Matt Cholick <mcholick@pivotal.io>

Add release notes for 0.8.x release

---

using.html.md.erb

Co-authored-by: Matt Cholick <mcholick@pivotal.io>

Add documentation on feature for CRD version validation on update

---

using.html.md.erb

Assigning ksm flags via environment variables 
Co-authored-by: Joe Eltgroth <jeltgroth@pivotal.io>

[#172031282] Assigning ksm flags via environment variables

---

installing.html.md.erb

[#172312256]
Co-authored-by: Matt Cholick <mcholick@pivotal.io>

Make the private registry configuration docs more accurate

---

managing-clusters.html.md

Should this be merged to any other branches? No, lastest for 0.9 is good.

Indicate valid characters for cluster name

---

troubleshoot.html.md.erb

New command for KSM version 0.9 to show ksm server logs. 
`ksm logs`

For 0.9 version. 

---

prepare-offer.html.md.erb

Move to ksm-sample repo.

---

troubleshoot.html.md.erb

Co-authored-by: Joe Eltgroth <jeltgroth@pivotal.io>
Should this be merged to any other branches? yes- all

add clean up script to troubleshooting section of the docs

---

prepare-offer.html.md.erb

Co-authored-by: Emily Johnson <ejohnson@pivotal.io>

Add some details around service credentials in charts

---

managing-clusters.html.md.erb

Fix the underscores that were escaped

---

prepare-offer.html.md.erb

[#172649627]
Co-authored-by: Emily Johnson<emjohnson@vmware.com>

Update for new test-bind-template argument

---

installing-helm.html.md.erb

Co-authored-by: Matt Cholick<mcholick@pivotal.io>
Should this be merged to any other branches? No

Add some clarity for helm install.

---

installing-helm.html.md.erb

prometheus instructions

---

installing-helm-lab.html.md.erb
installing-helm.html.md.erb

Fixing prometheus query

---

installing-helm.html.md.erb

Update for external Postgres

---

installing.html.md.erb

Co-authored-by: Matt Cholick<mcholick@vmware.com>
Should this be merged to any other branches? No

Add correct values for image credentials.

---

installing.html.md.erb

Document the command for loading tgz image files
[#173565725]
Should this be merged to any other branches? yes

Document the command for loading tgz image files

---

troubleshoot.html.md.erb

Removing  command ksm logs in favor of kubectl logs

Removing  command ksm logs in favor of kubectl logs

---

installing.html.md.erb

Co-authored-by: Ed King <eking@vmware.com>

Add missing namespace param on installation page

---

installing.html.md.erb

Co-authored-by: Ed King <eking@vmware.com>

Fix postgres image doc issues

---

index.html.md.erb

Co-authored-by: Ed King <eking@vmware.com>

Update limitation text

---

installing.html.md.erb

Signed-off-by: Sam Gunaratne <sgunaratne@vmware.com>

Remove redundant steps from helm install

---

installing-lab.html.md.erb
installing.html.md.erb
troubleshoot.html.md.erb
using.html.md.erb

Splitting production and lab into two different docs

---

installing.html.md.erb

> Should this be merged to any other branches?
Yes, `0.10.0`

Ingress isn't optional

---

installing-lab.html.md.erb
installing.html.md.erb

> Should this be merged to any other branches?
Yes, `0.10`
Co-authored-by: Maggie Ambrose <mambrose@vmware.com>

Document CF Permission

---

managing-clusters.html.md.erb

Co-authored-by: Maggie Ambrose <mambrose@vmware.com>
Yes, `0.10`

Create SA in dedicated namespace

---

installing-lab.html.md.erb
installing.html.md.erb

Should this be merged to any other branches? Nope
Fixing indentation and adding info about BROKER_IP for AWS

Fixing indentation and adding info about BROKER_IP for AWS

---

installing-lab.html.md.erb
installing.html.md.erb

Should this be merged to any other branches? Nope
Instruction to create container-services-manager` project in your registry (https://github.com/pivotal-cf/docs-ksm/issues/77)

instruction to create container-services-manager` project in your registry

---

installing-lab.html.md.erb

Nope
Instructions on how to install lab environment using install-lab.sh script

Instructions on how to install lab environment using install-lab.sh script

---

installing.html.md.erb

add definitions for TLS key and cert

---

installing-lab.html.md.erb

Adding new requirement

---

installing.html.md.erb

[#174253465]
Co-Authored-by: Emily Johnson <emjohnson@vmware.com>

Add the ability to use a cf client and secret rather than admin creds

---

installing-lab.html.md.erb

Some improvements on requirements

---

installing-dev.html.md.erb

Renaming installing lab to installing dev

---

README.md
installing-lab.html.md.erb
installing.html.md.erb
using.html.md.erb

Co-authored-by: Eduardo Oliveira<edeoliveira@vmware.com>
Should this be merged to any other branches? Yes

Rename product slug to tanzu-service-manager

---

prepare-offer.html.md.erb

Co-authored-by: Sam Gunaratne <sgunaratne@vmware.com>

ksm offer init now includes an overrides example file

---

README.md
about-offer.html.md.erb
architecture.html.md.erb
checklist.html.md.erb
configure-helm.html.md.erb
index.html.md.erb
installing-dev.html.md.erb
installing.html.md.erb
managing-clusters.html.md.erb
prepare-offer.html.md.erb
release-notes.html.md.erb
storage.html.md.erb
troubleshoot.html.md.erb
upgrading.html.md.erb
using.html.md.erb

Co-authored-by: Emily Johnson <emjohnson@vmware.com>

Renaming installing from KSM to Tanzu Service Manager / TSMGR standard

---

prepare-offer.html.md.erb

Co-authored-by: Joe Eltgroth <jeltgroth@vmware.com>
Should this be merged to any other branches? Yes

[#174481278] Improve test-bind-template doc

---

configure-helm.html.md.erb
prepare-offer.html.md.erb

Hi there, just a small URL update here.
Thanks!
Should this be merged to any other branches? No

Small update to git urls

---

using.html.md.erb

Co-authored-by: Emily Johnson <emjohnson@vmware.com>
> Yes - backport to `0.11` and `0.10`.

Add back in creds section (updated for k8s installation method)

---

installing.html.md.erb

> Yes, merge to other branches

Tanzunet now calls it "Artifact references"

---

release-notes.html.md.erb

Add new release notes.

---

installing.html.md.erb

Should this be merged to any other branches? Yes

Sorted cf configuration to be after configuring ingress.

---

installing-dev.html.md.erb
installing.html.md.erb

Specify the allowed characters for Helm release names

---

installing.html.md.erb
managing-clusters.html.md.erb
storage.html.md.erb

Hi there, just a few small fixes in this one.
Thanks!
Should this be merged to any other branches? nope!

Small fixes

---

configure-helm.html.md.erb
prepare-offer.html.md.erb

Co-authored-by: Eduardo Oliveira <edeoliveira@vmware.com>
> Yes

Edit placement and details of configing and preparing offers.

---

installing-dev.html.md.erb

Should this be merged to any other branches? yes

Fixed references to cf client and cf client secret

---

troubleshoot.html.md.erb

[#174627613]
Co-Authored-by: Emily Johnson <emjohnson@vmware.com>

Document timeout configuration

---

about-offer.html.md.erb
configure-helm.html.md.erb
prepare-offer.html.md.erb
troubleshoot.html.md.erb
using.html.md.erb

Co-authored-by: Sam Gunaratne <sgunaratne@vmware.com>
Should this be merged to any other branches? Y

Renaming from marketplaceName to offerName

---

installing-dev.html.md.erb
release-notes.html.md.erb

Should this be merged to any other branches? No

174819867 fix names

---

using.html.md.erb

I think this better reflects what the user is trying to achieve

Improve using page cli instruction title

---

installing.html.md.erb

No need to merge onto other branches

Recommend broker to cf over https

---

installing-dev.html.md.erb
installing.html.md.erb

Which other branches should this be merged with (if any)? no

Add helm show command

---

installing-dev.html.md.erb

Co-authored-by: Ed King <eking@vmware.com> 
Which other branches should this be merged with (if any)? No

Fix service name in BROKER_IP

---

installing.html.md.erb

Which other branches should this be merged with (if any)? None

Update ingress instructions to include path

---

index.html.md.erb
installing-dev.html.md.erb
installing.html.md.erb

[#174997515]
Co-authoredy-by: Joe Eltgroth <jeltgroth@vmware.com>
Which other branches should this be merged with (if any)? 0.11.27 and newer

document versions of k8s (1.16+) that TSMGR works against

---

managing-clusters.html.md.erb

[#175053653]
Co-Authored-by: Eduardo Oliveira <edeoliveira@vmware.com>
Which other branches should this be merged with (if any)? 0.11.27+

remove unnecessary line

---

release-notes.html.md.erb
using.html.md.erb

Add documentation around token authentiation

---

installing.html.md.erb

[#175077587]
Co-Authored-by: Eduardo Oliveira <edeoliveira@vmware.com>
Which other branches should this be merged with (if any)? none, only the latest

Clarify cf client/clientSecret or username/password credentials

---

configure-helm.html.md.erb
installing-dev.html.md.erb
installing.html.md.erb
prepare-offer.html.md.erb
troubleshoot-techniques.html.md.erb
using.html.md.erb

[#175054196]
[#174752332]
[#174735420]
[#174733932]
[#174730669]
Which other branches should this be merged with (if any)? No

Misc docs improvements

---

upgrading.html.md.erb

[#175056683]
Co-authored-by: Joe Eltgroth <jeltgroth@vmware.com>
Which other branches should this be merged with (if any)? No other branches

Update "Upgrading TSMGR" docs section

---

installing.html.md.erb

[#174793851]
Co-authored-by: Emily Johnson <emjohnson@vmware.com>
Which other branches should this be merged with (if any)? None

Prometheus coming from the wrong spot.

---

installing.html.md.erb

Which other branches should this be merged with (if any)? - No other branches
Thanks docs team!

Add ingress warnings around istio ingress differencs

---

installing.html.md.erb

[#174793851]
During the tests I realized the name ends with "-tsmgr", so changed the query to be more generic.
Which other branches should this be merged with (if any)? nope

Fixing the query to be more generic.

---

installing.html.md.erb

Co-Authored-by: Eduardo Oliveira <edeoliveira@vmware.com>
Which other branches should this be merged with (if any)? none

Make ingress docs better

---

index.html.md.erb
installing-dev.html.md.erb
installing.html.md.erb

Merge requirements sections

---

installing.html.md.erb

Replace Linkerd with Istio

---

installing.html.md.erb

Which other branches should this be merged with (if any)?

Fix docker command

---

checklist.html.md.erb

Update the Getting started page

---

installing-dev.html.md.erb
release-notes.html.md.erb

Which other branches should this be merged with (if any)? No

Release notes for 1.0.11

---

index.html.md.erb

Which other branches should this be merged with (if any)?

Updating feedback email address

---

installing.html.md.erb

Which other branches should this be merged with (if any)? 1.0.11

Removing reference to tgz files that are no more used in tsmgr

---

installing-dev.html.md.erb

correct the namespace that the dev script uses

---

using.html.md.erb

Hey docs team,
Just a small quick fix to one of the commands here.
Cheers,
Ed

Small fix to offer save command
